### ISSUE TITLE
Add documentation on what is implemented and what isn't

### ISSUE THREAD

**Issue by TheBloodMan49** [Dwight-Studio/JArmEmu#1]
I think it would help end users know if it will do the job without having to install it and test everything

**Comment by FoxYinx** [comment]
Hi, I added a markdown file referencing every implemented instruction, hope it will help people!
Will work on improving it in next releases!

**Comment by Deleranax** [comment]
All the instructions are now automatically added to the in-app instruction list (Help>See instructions...).
