### ISSUE TITLE
Annoying code suggestions

### ISSUE THREAD

**Issue by Ecnama** [Dwight-Studio/JArmEmu#18]
When pressing <enter> before pseudo-operations, suggestions pop up and are selected. If <enter> is pressed again, it fills with the suggestion instead of starting a new line.

**Comment by Deleranax** [comment]
Thank you for reporting this issue! We managed to reproduce it, and we are working on a fix.

**Comment by Deleranax** [comment]
This is not restricted to pseudo-instruction, pressing enter before any token will trigger the autocompletion.
