### ISSUE TITLE
Make ctrl + / comment all selected lines

### ISSUE THREAD

**Issue by pixup1** [Dwight-Studio/JArmEmu#29]
Enhancement suggestion: when you press ctrl + /, it comments all the lines that are selected from the beginning of the line, and when you press it again it uncomments them.

This is a very useful feature in VSCode and it would be nifty in assembly, especially since there are no multi-line comments.

**Comment by Deleranax** [comment]
The problem with using `Ctrl + /` as a shortcut is that you can't activate it on an azerty keyboard (and similarly `Ctrl + :` doesn't work on qwerty). JavaFx doesn't take this into account when managing shortcuts.
